apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-hello-world-api
spec:
  selector:
    matchLabels:
      app: dotnet-hello-world-api
  replicas: 3
  template:
    metadata:
      labels:
        app: dotnet-hello-world-api
    spec:
      containers:
      - name: dotnet-hello-world-api
        image: ghcr.io/mapaille/dotnet-hello-world-api
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
        livenessProbe:
          httpGet:
            path: /live
            port: 80
